version: '3.7'

services:
  frontend:
    container_name: frontend
    image: saulguz1/frontfinalsopes
    build: ./Frontend
    ports: 
      - '80:80'
    links: 
      - apinode

  apinode: 
    container_name: apinode
    image: saulguz1/backfinalsopes
    build: ./Backend
    expose:
      - "9000"
    ports: 
      - "9000:9000"